package com.ort.tp_ort_tp3_app_gestordenotas.entities

enum class AnioMateria {
    PRIMER_ANIO_PRIMER_CUATRIMESTRE,
    PRIMER_ANIO_SEGUNDO_CUATRIMESTRE,
    SEGUNDO_ANIO_PRIMER_CUATRIMESTRE,
    SEGUNDO_ANIO_SEGUNDO_CUATRIMESTRE
}